package com.dpad.messaging.helpers

import android.content.Context
import android.graphics.Color
import android.graphics.drawable.Drawable
import android.graphics.drawable.GradientDrawable
import android.graphics.drawable.StateListDrawable
import android.view.Gravity
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import androidx.appcompat.app.AlertDialog
import androidx.core.graphics.ColorUtils
import androidx.recyclerview.widget.GridLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.dpad.messaging.R

/**
 * Per-contact message colors.
 *
 * The user can pick a color for a phone number; that color is used for the
 * conversation avatar and for that contact's received message bubbles.
 * Colors are keyed by the normalized (digits-only) phone number.
 */
object ContactColors {

    /** Just a load of colors. No clue how well they work in different contexts I just really love colors. */
    val PALETTE = intArrayOf(
        // Palettes generated by tailwind option of https://htmlcolorcodes.com/color-picker/ 100--800 in 100 step increments
        0xFFFFB8B8.toInt(), // Reds FF0000
        0xFFFF8A8A.toInt(),
        0xFFFF5C5C.toInt(),
        0xFFFF2E2E.toInt(),
        0xFFFF0000.toInt(),
        0xFFD10000.toInt(),
        0xFFA30000.toInt(),
        0xFF750000.toInt(),
        0xFFFFDBB8.toInt(), // Oranges FF8000
        0xFFFFC48A.toInt(),
        0xFFFFAD5C.toInt(),
        0xFFFF962E.toInt(),
        0xFFD16900.toInt(),
        0xFFA35200.toInt(),
        0xFFA35200.toInt(),
        0xFF753B00.toInt(),
        0xFFFFF8B8.toInt(), // Yellows FFE600
        0xFFFFF38A.toInt(),
        0xFFFFEF5C.toInt(),
        0xFFFFEA2E.toInt(),
        0xFFFFE600.toInt(),
        0xFFD1BC00.toInt(),
        0xFFA39300.toInt(),
        0xFF756A00.toInt(),
        0xFFC2FFB8.toInt(), // Greens 26FF00
        0xFF9BFF8A.toInt(),
        0xFF74FF5C.toInt(),
        0xFF4DFF2E.toInt(),
        0xFF26FF00.toInt(),
        0xFF1FD100.toInt(),
        0xFF18A300.toInt(),
        0xFF127500.toInt(),
        0xFFD9EEC9.toInt(), // Greens D9EEC9
        0xFFC0E3A6.toInt(),
        0xFFA8D883.toInt(),
        0xFF8FCD60.toInt(),
        0xFF83C74E.toInt(),
        0xFF619F32.toInt(),
        0xFF4C7C27.toInt(),
        0xFF37591C.toInt(),
        0xFFB8DAFF.toInt(), // Blues 007BFF
        0xFF8AC2FF.toInt(),
        0xFF5CABFF.toInt(),
        0xFF2E93FF.toInt(),
        0xFF007BFF.toInt(),
        0xFF0065D1.toInt(),
        0xFF004FA3.toInt(),
        0xFF003975.toInt(),
        0xFFE0B8FF.toInt(), // Purples 9000FF
        0xFFCC8AFF.toInt(),
        0xFFB85CFF.toInt(),
        0xFFA42EFF.toInt(),
        0xFF9000FF.toInt(),
        0xFF7600D1.toInt(),
        0xFF5C00A3.toInt(),
        0xFF420075.toInt(),
        0xFFFFB8F3.toInt(), // Pinks FF00D4
        0xFFFF8AEB.toInt(),
        0xFFFF5CE4.toInt(),
        0xFFFF2EDC.toInt(),
        0xFFFF00D4.toInt(),
        0xFFD100AE.toInt(),
        0xFFA30088.toInt(),
        0xFF750062.toInt(),
        0xFFDBDBDB.toInt(), // Grays 808080
        0xFFC4C4C4.toInt(),
        0xFFADADAD.toInt(),
        0xFF969696.toInt(),
        0xFF808080.toInt(),
        0xFF696969.toInt(), // hehe
        0xFF525252.toInt(),
        0xFF3B3B3B.toInt(),
        // Black & White
        0xFF000000.toInt(), // Black
        0xFFFFFFFF.toInt(), // White
        // Options from regular app
        0xFFE53935.toInt(), // Red
        0xFFD81B60.toInt(), // Pink
        0xFF8E24AA.toInt(), // Purple
        0xFF5E35B1.toInt(), // Deep Purple
        0xFF3949AB.toInt(), // Indigo
        0xFF1E88E5.toInt(), // Blue
        0xFF0097A7.toInt(), // Cyan
        0xFF00897B.toInt(), // Teal
        0xFF43A047.toInt(), // Green
        0xFF7CB342.toInt(), // Light Green
        0xFFF4511E.toInt(), // Deep Orange
        0xFF6D4C41.toInt(),  // Brown
        // Dark mode accent colors (blue/green/orange/rose)
        // If there's a way to make these references to Colors.xml I don't know it but that would be better.
        0xFF1A73E8.toInt(), // Regular
        0xFF20B26B.toInt(),
        0xFFF39C3D.toInt(),
        0xFFE1608E.toInt(),
        0xFF1557B0.toInt(), // Dark
        0xFF198954.toInt(),
        0xFFC27B2F.toInt(),
        0xFFB54D72.toInt(),
        0xFF7A1A73E8.toInt(), // Highlight
        0xFF7A20B26B.toInt(),
        0xFF7AF39C3D.toInt(),
        0xFF7AE1608E.toInt(),
        // Light mode accent colors (blue/green/orange/rose)
        0xFF1A73E8.toInt(), // Regular
        0xFF1B9E5A.toInt(),
        0xFFE67E22.toInt(),
        0xFFD64574.toInt(),
        0xFF1557B0.toInt(), // Dark
        0xFF157C46.toInt(),
        0xFFB76116.toInt(),
        0xFFA83459.toInt(),
        0xFF661A73E8.toInt(), // Highlight
        0xFF661B9E5A.toInt(),
        0xFF66E67E22.toInt(),
        0xFF66D64574.toInt(),
        0xFF42A5F5.toInt(), // Focused
        0xFF2ECC71.toInt(),
        0xFFF39C3D.toInt(),
        0xFFE1608E.toInt()

    )

    private const val COLUMNS = 4

    /** Digits-only form used as the storage key. */
    fun normalize(phoneNumber: String): String =
        phoneNumber.filter { it.isDigit() }.ifBlank { phoneNumber.trim() }

    /** User-assigned color for [phoneNumber], or null if unset. */
    fun customColor(phoneNumber: String): Int? =
        Prefs.get().getContactColor(normalize(phoneNumber))

    /**
     * Best color for [phoneNumber] = custom color if set,
     * otherwise a stable hash-derived color (so untouched contacts still look nice).
     */
    fun resolveColor(phoneNumber: String): Int =
        customColor(phoneNumber) ?: defaultFor(phoneNumber)

    /** Stable, readable HSL colour derived from a seed string (number or name). */
    fun defaultFor(seed: String): Int {
        val hue = (Math.abs(seed.hashCode()) % 360).toFloat()
        return ColorUtils.HSLToColor(floatArrayOf(hue, 0.55f, 0.35f))
    }

    /** High-contrast text colour to place on top of [background]. */
    fun textColorOn(background: Int): Int =
        if (ColorUtils.calculateLuminance(background) < 0.5) Color.WHITE else 0xFF1B1F24.toInt()

    /** Slightly transparent meta colour to place on top of [background]. */
    fun metaColorOn(background: Int): Int =
        if (ColorUtils.calculateLuminance(background) < 0.5) 0xCCFFFFFF.toInt() else 0xAA1B1F24.toInt()

    // ── Drawables ───────────────────────────────────────────────────────────

    private fun roundedRect(color: Int, radiusDp: Float, strokeWidth: Int): GradientDrawable =
        GradientDrawable().apply {
            shape = GradientDrawable.RECTANGLE
            setColor(color)
            cornerRadius = radiusDp
            if (strokeWidth > 0) setStroke(strokeWidth, 0xFF00FFFF.toInt())
        }

    /** Rounded-square swatch that shows the app's cyan focus ring when focused. */
    fun swatchDrawable(color: Int): Drawable {
        val normal = roundedRect(color, 8f, 0)
        val focused = roundedRect(color, 8f, 7)
        return StateListDrawable().apply {
            addState(intArrayOf(android.R.attr.state_focused), focused)
            addState(IntArray(0), normal)
        }
    }

    /**
     * Received-bubble background using [color]. Overall shape matches
     * drawable/bubble_received.xml; focus state adds the cyan ring.
     */
    fun receivedBubbleDrawable(color: Int): Drawable {
        val normal = roundedRect(color, 0f, 0).apply {
            cornerRadii = floatArrayOf(10f, 10f, 10f, 10f, 10f, 10f, 2f, 2f)
        }
        val focused = roundedRect(color, 0f, 7).apply {
            cornerRadii = floatArrayOf(10f, 10f, 10f, 10f, 10f, 10f, 2f, 2f)
        }
        return StateListDrawable().apply {
            addState(intArrayOf(android.R.attr.state_focused), focused)
            addState(IntArray(0), normal)
        }
    }

    // ── Picker dialog ───────────────────────────────────────────────────────

    /**
     * Shows a D-Pad-friendly color picker.
     * [currentColor] selects the matching swatch when the dialog opens;
     * [onSelected] receives the chosen color, or null to clear back to default.
     */
    fun showColorPicker(
        context: Context,
        title: String,
        currentColor: Int?,
        onSelected: (Int?) -> Unit
    ) {
        val density = context.resources.displayMetrics.density
        val spacingPx = (density * 8f).toInt()
        val paddingPx = (density * 16f).toInt()

        val colors = PALETTE.toList() + null  // null represents "default"
        val columns = 4

        val recycler = RecyclerView(context).apply {
            layoutManager = GridLayoutManager(context, columns)
            adapter = ColorPickerAdapter(colors, currentColor, onSelected)
            setPadding(paddingPx, paddingPx, paddingPx, paddingPx)
            addItemDecoration(SwatchItemDecoration(spacingPx))
            // Limit max height to fit on small screens (Sonim XP3900: 320dp height)
            val maxHeight = (context.resources.displayMetrics.heightPixels * 0.7f).toInt()
            layoutParams = ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.WRAP_CONTENT
            ).also { params ->
                params.height = maxHeight.coerceAtMost(params.height)
            }
        }

        val dialog = AlertDialog.Builder(context)
            .setTitle(title)
            .setView(recycler)
            .setNegativeButton(android.R.string.cancel, null)
            .create()

        dialog.setOnShowListener {
            val target = currentColor?.let { PALETTE.indexOf(it) } ?: colors.size - 1
            recycler.layoutManager?.scrollToPosition(target)
            recycler.getChildAt(0)?.requestFocus()
            // Ensure dialog fits on screen
            dialog.window?.apply {
                setLayout(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.WRAP_CONTENT
                )
                // Limit height to 70% of screen height
                val maxHeight = (context.resources.displayMetrics.heightPixels * 0.7f).toInt()
                if (attributes.height > maxHeight) {
                    attributes.height = maxHeight
                }
            }
        }

        dialog.show()
    }

    private class ColorPickerAdapter(
        private val colors: List<Int?>,
        private val currentColor: Int?,
        private val onSelected: (Int?) -> Unit
    ) : RecyclerView.Adapter<ColorPickerAdapter.ViewHolder>() {

        override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
            val density = parent.context.resources.displayMetrics.density
            val swatchSizePx = (density * 48f).toInt()
            val view = View(parent.context).apply {
                layoutParams = ViewGroup.LayoutParams(swatchSizePx, swatchSizePx)
                isFocusable = true
                isFocusableInTouchMode = true
            }
            return ViewHolder(view)
        }

        override fun onBindViewHolder(holder: ViewHolder, position: Int) {
            val color = colors[position]
            holder.itemView.apply {
                background = if (color != null) swatchDrawable(color) else swatchDrawable(0xFF607D8B.toInt())
                setOnClickListener {
                    onSelected(color)
                }
                if (color == currentColor) {
                    requestFocus()
                }
            }
        }

        override fun getItemCount() = colors.size

        class ViewHolder(view: View) : RecyclerView.ViewHolder(view)
    }

    private class SwatchItemDecoration(private val spacingPx: Int) :
        RecyclerView.ItemDecoration() {
        override fun getItemOffsets(outRect: android.graphics.Rect, view: View, parent: RecyclerView, state: RecyclerView.State) {
            outRect.set(spacingPx, spacingPx, spacingPx, spacingPx)
        }
    }
}